// 앱에서 쓰는 Material Symbols 아이콘 이름 목록.
// <Icon name="..."> 의 name 은 이 목록의 값만 허용되고(IconName 타입), vite.config.ts 는 이 목록으로
// 아이콘 폰트 서브셋 URL 을 만들어 index.html 에 주입한다. 전체 폰트는 5MB 가 넘지만 서브셋은 수십 KB 다.
// 새 아이콘을 쓰려면 여기에 이름을 추가하면 된다. 목록에 없는 이름은 타입 오류가 나고, 폰트에도 없어 글자로 보인다.
export const ICON_NAMES = [
  'arrow_back',
  'article',
  'attach_file',
  'badge',
  'bar_chart',
  'calendar_view_week',
  'campaign',
  'check',
  'check_circle',
  'chevron_right',
  'content_copy',
  'download',
  'error',
  'event_available',
  'event_busy',
  'event_note',
  'expand_less',
  'expand_more',
  'format_list_bulleted',
  'grid_view',
  'home',
  'hourglass_empty',
  'inbox',
  'info',
  'ios_share',
  'location_on',
  'lock',
  'no_meals',
  'person',
  'print',
  'push_pin',
  'restaurant',
  'schedule',
  'school',
  'search',
  'tag',
  'timer',
  'timer_off',
  'visibility',
  'visibility_off',
  'warning',
  'workspace_premium',
] as const

export type IconName = (typeof ICON_NAMES)[number]
